export const usStatesArray = [
  {id: 1, 
  name: 'Alabama', 
  abbreviation: 'AL', 
  capital: 'Montgomery	', 
  largestcity: 'Birmingham', 
  nationalparks: [{id: 1-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 2, 
  name: 'Alaska', 
  abbreviation: 'AK', 
  capital: 'Juneau', 
  largestcity: 'Anchorage', 
  nationalparks: [{id: 2-11, name: 'Denali National Park and Preserve'}, {id: 2-12, name: 'Gates of the Arctic National Park and Preserve'}, {id: 2-13, name: 'Glacier Bay National Park and Preserve'}, {id: 2-14, name: 'Katmai National Park and Preserve'}, {id: 2-15, name: 'Kenai Fjords National Park'}, {id: 2-16, name: 'Kobuk Valley National Park'}, {id: 2-17, name: 'Lake Clark National Park and Preserve'}, {id: 2-18, name: 'Wrangell–St. Elias National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 3, 
  name:'Arizona', 
  abbreviation: 'AZ', 
  capital: 'Phoenix', 
  largestcity: 'Phoenix', 
  nationalparks: [{id: 3.11, name: 'Grand Canyon National Park'}, {id: 3.12, name: 'Petrified Forest National Park'}, {id: 3.13, name: 'Saguaro National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 4, 
  name:'Arkansas', 
  abbreviation: 'AR', 
  capital: 'Little Rock	', 
  largestcity: 'Little Rock	', 
  nationalparks: [{id: 4.11, name: 'Hot Springs National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 5, 
  name: 'California', 
  abbreviation: 'CA', 
  capital: 'Sacramento', 
  largestcity: 'Los Angeles', 
  nationalparks: [{id: 5.11, name: 'Channel Islands National Park'}, {id: 5.12, name: 'Death Valley National Park'}, {id: 5.13, name: 'Joshua Tree National Park'}, {id: 5.14, name: 'Kings Canyon National Park'}, {id: 5.15, name: 'Lassen Volcanic National Park'}, {id: 5.16, name: 'Pinnacles National Park'}, {id: 5.17, name: 'Redwood National & State Parks'}, {id: 5.18, name: 'Sequoia National Park'}, {id: 5.19, name: 'Yosemite National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 6, 
  name: 'Colorado', 
  abbreviation: 'CO', 
  capital: 'Denver', 
  largestcity: 'Denver', 
  nationalparks: [{id: 6.11, name: 'Black Canyon of the Gunnison National Park'}, {id: 6.12, name: 'Great Sand Dunes National Park'}, {id: 6.13, name: 'Mesa Verde National Park'}, {id: 6.14, name: 'Rocky Mountain National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 7, 
  name: 'Connecticut', 
  abbreviation: 'CT', 
  capital: 'Hartford', 
  largestcity: 'Bridgeport', 
  nationalparks: [{id: 7-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 8, 
  name: 'Delaware', 
  abbreviation: 'DE', 
  capital: 'Dover', 
  largestcity: 'Wilmington', 
  nationalparks: [{id: 8-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 9, 
  name: 'Florida', 
  abbreviation: 'FL', 
  capital: 'Tallahassee', 
  largestcity: 'Jacksonville', 
  nationalparks: [{id: 9.11, name: 'Biscayne National Park'}, {id: 9.12, name: 'Dry Tortugas National Park'}, {id: 9.13, name: 'Everglades National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 10, 
  name: 'Georgia', 
  abbreviation: 'GA', 
  capital: 'Atlanta', 
  largestcity: 'Atlanta', 
  nationalparks: [{id: 10-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 11, 
  name: 'Hawaii', 
  abbreviation: 'HI', 
  capital: 'Honolulu', 
  largestcity: 'Honolulu', 
  nationalparks: [{id: 11.11, name: 'Haleakalā National Park'}, {id: 11.12, name: 'Hawai’i Volcanoes National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 12, 
  name: 'Idaho', 
  abbreviation: 'ID', 
  capital: 'Boise', 
  largestcity: 'Boise', 
  nationalparks: [{id: 12.11, name: 'Yellowstone National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 13, 
  name: 'Illinois', 
  abbreviation: 'IL', 
  capital: 'Springfield', 
  largestcity: 'Chicago', 
  nationalparks: [{id: 13-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 14, 
  name: 'Indiana', 
  abbreviation: 'IN', 
  capital: 'Indianapolis', 
  largestcity: 'Indianapolis', 
  nationalparks: [{id: 14.11, name: 'Indiana Dunes National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 15, 
  name: 'Iowa', 
  abbreviation: 'IA', 
  capital: 'Des Moines', 
  largestcity: 'Des Moines', 
  nationalparks: [{id: 15-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},
  
  {id: 16, 
  name: 'Kansas', 
  abbreviation: 'KS', 
  capital: 'Topeka', 
  largestcity: 'Wichita', 
  nationalparks: [{id: 16-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 17, 
  name: 'Kentucky', 
  abbreviation: 'KY', 
  capital: 'Frankfort', 
  largestcity: 'Louisville', 
  nationalparks: [{id: 17.11, name: 'Mammoth Cave National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 18, 
  name: 'Louisiana', 
  abbreviation: 'LA', 
  capital: 'Baton Rouge', 
  largestcity: 'New Orleans', 
  nationalparks: [{id: 18-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 19, 
  name: 'Maine', 
  abbreviation: 'ME', 
  capital: 'Augusta', 
  largestcity: 'Portland', 
  nationalparks: [{id: 19.11, name: 'Acadia National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 20, 
  name: 'Maryland', 
  abbreviation: 'MD', 
  capital: 'Annapolis', 
  largestcity: 'Baltimore', 
  nationalparks: [{id: 20-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 21, 
  name: 'Massachusetts', 
  abbreviation: 'MA', 
  capital: 'Boston', 
  largestcity: 'Boston', 
  nationalparks: [{id: 21-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 22, 
  name: 'Michigan', 
  abbreviation: 'MI', 
  capital: 'Lansing	', 
  largestcity: 'Detroit', 
  nationalparks: [{id: 22.11, name: 'Isle Royale National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 23, 
  name: 'Minnesota', 
  abbreviation: 'MN', 
  capital: 'St. Paul', 
  largestcity: 'Minneapolis', 
  nationalparks: [{id: 23.11, name: 'Voyageurs National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 24, 
  name: 'Mississippi', 
  abbreviation: 'MS', 
  capital: 'Jackson', largestcity: 'Jackson', 
  nationalparks: [{id: 24-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 25, 
  name: 'Missouri', 
  abbreviation: 'MO', 
  capital: 'Jefferson City', 
  largestcity: 'Kansas City', 
  nationalparks: [{id: 25.11, name: 'Gateway Arch National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 26, 
  name: 'Montana', 
  abbreviation: 'MT', 
  capital: 'Helena', 
  largestcity: 'Billings', 
  nationalparks: [{id: 26.11, name: 'Glacier National Park'}, {id: 26.12, name: 'Yellowstone National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 27, 
  name: 'Nebraska', 
  abbreviation: 'NE', 
  capital: 'Lincoln', 
  largestcity: 'Omaha', 
  nationalparks: [{id: 27-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 28, 
  name: 'Nevada', 
  abbreviation: 'NV', 
  capital: 'Carson City', 
  largestcity: 'Las Vegas', 
  nationalparks: [{id: 28.11, name: 'Death Valley National Park'}, {id: 28.12, name: 'Great Basin National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 29, 
  name: 'New Hampshire', 
  abbreviation: 'NH', 
  capital: 'Concord', 
  largestcity: 'Manchester', 
  nationalparks: [{id: 29-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 30, 
  name: 'New Jersey', 
  abbreviation: 'NJ', 
  capital: 'Trenton', 
  largestcity: 'Newark', 
  nationalparks: [{id: 30-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 31, 
  name: 'New Mexico', 
  abbreviation: 'NM', 
  capital: 'Santa Fe', 
  largestcity: 'Albuquerque', 
  nationalparks: [{id: 31.11, name: 'Carlsbad Caverns National Park'}, {id: 31.12, name: 'White Sands National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 32, 
  name: 'New York', 
  abbreviation: 'NY', 
  capital: 'Albany', 
  largestcity: 'New York City', 
  nationalparks: [{id: 32-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 33, 
  name: 'North Carolina', 
  abbreviation: 'NC', 
  capital: 'Raleigh', 
  largestcity: 'Charlotte', 
  nationalparks: [{id: 33.11, name: 'Great Smoky Mountains National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 34, 
  name: 'North Dakota', 
  abbreviation: 'ND', 
  capital: 'Bismarck', 
  largestcity: 'Fargo', 
  nationalparks: [{id: 34.11, name: 'Theodore Roosevelt National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 35, 
  name: 'Ohio', 
  abbreviation: 'OH', 
  capital: 'Columbus', 
  largestcity: 'Columbus', 
  nationalparks: [{id: 35.11, name: 'Cuyahoga Valley National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 36, 
  name: 'Oklahoma', 
  abbreviation: 'OK', 
  capital: 'Oklahoma City', 
  largestcity: 'Oklahoma City', 
  nationalparks: [{id: 36-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 37, 
  name: 'Oregon', 
  abbreviation: 'OR', 
  capital: 'Salem', 
  largestcity: 'Portland', 
  nationalparks: [{id: 37.11, name: 'Crater Lake National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 38, 
  name: 'Pennsylvania', 
  abbreviation: 'PA', 
  capital: 'Harrisburg', 
  largestcity: 'Philadelphia', 
  nationalparks: [{id: 38-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 39, 
  name: 'Rhode Island', 
  abbreviation: 'RI', 
  capital: 'Providence', 
  largestcity: 'Providence', 
  nationalparks: [{id: 39-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 40, 
  name: 'South Carolina', 
  abbreviation: 'SC', 
  capital: 'Columbia', 
  largestcity: 'Columbia', 
  nationalparks: [{id: 40.11, name: 'Congaree National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},
  
  {id: 41, 
  name: 'South Dakota', 
  abbreviation: 'SD', 
  capital: 'Pierre', 
  largestcity: 'Sioux Falls', 
  nationalparks: [{id: 41.11, name: 'Badlands National Park'}, {id: 41.12, name: 'Wind Cave National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 42, 
  name: 'Tennessee', 
  abbreviation: 'TN', 
  capital: 'Nashville', 
  largestcity: 'Memphis', 
  nationalparks: [{id: 42.11, name: 'Great Smoky Mountains National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 43, 
  name: 'Texas', 
  abbreviation: 'TX', 
  capital: 'Austin', 
  largestcity: 'Houston', 
  nationalparks: [{id: 43.11, name: 'Big Bend National Park'}, {id: 43.12, name: 'Guadalupe Mountains National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 44, 
  name: 'Utah', 
  abbreviation: 'UT', 
  capital: 'Salt Lake City', 
  largestcity: 'Salt Lake City', 
  nationalparks: [{id: 45.11, name: 'Arches National Park'}, {id: 45.12, name: 'Bryce Canyon National Park'}, {id: 45.13, name: 'Canyonlands National Park'}, {id: 45.14, name: 'Capitol Reef National Park'}, {id: 45.15, name: 'Zion National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 45, 
  name: 'Vermont', 
  abbreviation: 'VT', 
  capital: 'Montpelier', 
  largestcity: 'Burlington', 
  nationalparks: [{id: 45-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 46, 
  name: 'Virginia', 
  abbreviation: 'VA', 
  capital: 'Richmond', 
  largestcity: 'Virginia Beach', 
  nationalparks: [{id: 46.11, name: 'Shenandoah National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 47, 
  name: 'Washington', 
  abbreviation: 'WA', 
  capital: 'Olympia', 
  largestcity: 'Seattle', 
  nationalparks: [{id: 47.11, name: 'Mount Rainier National Park'}, {id: 47.12, name: 'North Cascades National Park'}, {id: 47.13, name: 'Olympic National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 48, 
  name: 'West Virginia', 
  abbreviation: 'WV', 
  capital: 'Charleston', 
  largestcity: 'Charleston', 
  nationalparks: [{id: 48.11, name: 'New River Gorge National Park and Preserve'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 49, 
  name: 'Wisconsin', 
  abbreviation: 'WI', 
  capital: 'Madison', 
  largestcity: 'Milwaukee', 
  nationalparks: [{id: 49-11, name: 'null'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]},

  {id: 50, 
  name: 'Wyoming', 
  abbreviation: 'WY', 
  capital: 'Cheyenne', 
  largestcity: 'Cheyenne', 
  nationalparks: [{id: 50.11, name: 'Grand Teton National Park'}, {id: 50.12, name: 'Yellowstone National Park'}],
  attractions: [{id: 1-21, name: ''}, {id: 1-22, name: ''}, {id: 1-23, name: ''}, {id: 1-24, name: ''}, {id: 1-25, name: ''}], 
  other: [{id: 1-31, name: ''}, {id: 1-32, name: ''}, {id: 1-33, name: ''}, {id: 1-34, name: ''}, {id: 1-35, name: ''}]}
];