export const usStatesArray = [
    {id: 1, name: 'Alabama', abbreviation: 'AL', nationalparks: [{id: 1-11, name: 'a'}, {id: 1-12, name: 'b'}, {id: 1-13, name: 'c'}]},
    {id: 2, name: 'Alaska', abbreviation: 'AK', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 3, name:'Arizona', abbreviation: 'AZ', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 4, name:'Arkansas', abbreviation: 'AR', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 5, name: 'California', abbreviation: 'CA', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 6, name: 'Colorado', abbreviation: 'CO', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 7, name: 'Connecticut', abbreviation: 'CT', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 8, name: 'Delaware', abbreviation: 'DE', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 9, name: 'Florida', abbreviation: 'FL', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 10, name: 'Georgia', abbreviation: 'GA', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 11, name: 'Hawaii', abbreviation: 'HI', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 12, name: 'Idaho', abbreviation: 'ID', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 13, name: 'Illinois', abbreviation: 'IL', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 14, name: 'Indiana', abbreviation: 'IN', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 15, name: 'Iowa', abbreviation: 'IA', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 16, name: 'Kansas', abbreviation: 'KS', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 17, name: 'Kentucky', abbreviation: 'KY', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 18, name: 'Louisiana', abbreviation: 'LA', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 19, name: 'Maine', abbreviation: 'ME', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 20, name: 'Maryland', abbreviation: 'MD', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 21, name: 'Massachusetts', abbreviation: 'MA', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 22, name: 'Michigan', abbreviation: 'MI', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 23, name: 'Minnesota', abbreviation: 'MN', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 24, name: 'Mississippi', abbreviation: 'MS', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 25, name: 'Missouri', abbreviation: 'MO', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 26, name: 'Montana', abbreviation: 'MT', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 27, name: 'Nebraska', abbreviation: 'NE', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 28, name: 'Nevada', abbreviation: 'NV', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 29, name: 'New Hampshire', abbreviation: 'NH', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 30, name: 'New Jersey', abbreviation: 'NJ', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 31, name: 'New Mexico', abbreviation: 'NM', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 32, name: 'New York', abbreviation: 'NY', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 33, name: 'North Carolina', abbreviation: 'NC', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 34, name: 'North Dakota', abbreviation: 'ND', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 35, name: 'Ohio', abbreviation: 'OH', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 36, name: 'Oklahoma', abbreviation: 'OK', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 37, name: 'Oregon', abbreviation: 'OR', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 38, name: 'Pennsylvania', abbreviation: 'PA', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 39, name: 'Rhode Island', abbreviation: 'RI', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 40, name: 'South Carolina', abbreviation: 'SC', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 41, name: 'South Dakota', abbreviation: 'SD', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 42, name: 'Tennessee', abbreviation: 'TN', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 43, name: 'Texas', abbreviation: 'TX', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 44, name: 'Utah', abbreviation: 'UT', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 45, name: 'Vermont', abbreviation: 'VT', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 46, name: 'Virginia', abbreviation: 'VA', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 47, name: 'Washington', abbreviation: 'WA', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 48, name: 'West Virginia', abbreviation: 'WV', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 49, name: 'Wisconsin', abbreviation: 'WI', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]},
    {id: 50, name: 'Wyoming', abbreviation: 'WY', nationalparks: [{id: 1.01, name: 'a'}, {id: 1.02, name: 'b'}, {id: 1.03, name: 'c'}]}
  ];