export const usStatesArray = [
  {id: '1', 
  name: 'Alabama', 
  abbreviation: 'AL', 
  capital: [{id: '1-c', name: 'Montgomery'}], 
  largestcity: [{id: '1-lc', name: 'Birmingham'}], 
  nationalparks: [{id: '1-11', name: 'null'}],
  attractions: [{id: '1-21', name: 'U.S. Space & Rocket Center'}, {id: '1-22', name: 'Birmingham Civil Rights Institute'}, {id: '1-23', name: 'Cathedral Caverns State Park'}, {id: '1-24', name: 'Golf Shores'}], 
  other: [{id: '1-31', name: 'Eat Alabama BBQ'}, {id: '1-32', name: 'Eat Shrimp and Grits'}]},

  {id: '2', 
  name: 'Alaska', 
  abbreviation: 'AK', 
  capital: [{id: '2-c', name: 'Juneau'}], 
  largestcity: [{id: '2-lc', name: 'Anchorage'}], 
  nationalparks: [{id: '2-11', name: 'Denali National Park and Preserve'}, {id: '2-12', name: 'Gates of the Arctic National Park and Preserve'}, {id: '2-13', name: 'Glacier Bay National Park and Preserve'}, {id: '2-14', name: 'Katmai National Park and Preserve'}, {id: '2-15', name: 'Kenai Fjords National Park'}, {id: '2-16', name: 'Kobuk Valley National Park'}, {id: '2-17', name: 'Lake Clark National Park and Preserve'}, {id: '2-18', name: 'Wrangell–St. Elias National Park'}],
  attractions: [{id: '2-21', name: 'Anchorage Museum'}, {id: '2-22', name: 'Kodiak Island'}, {id: '2-23', name: 'Drive The Alcan Highway'}], 
  other: [{id: '2-31', name: 'Spot The Big 5 (Moose, Grizzly Bears, Caribou, Dall Sheep, Gray Wolves)'}, {id: '2-32', name: 'Kayak or Canoe'}, {id: '2-33', name: 'See The Northern Lights'}]},

  {id: '3', 
  name:'Arizona', 
  abbreviation: 'AZ', 
  capital: [{id: '3-c', name: 'Phoenix'}], 
  largestcity: [{id: '3-lc', name: 'Phoenix'}], 
  nationalparks: [{id: '3-11', name: 'Grand Canyon National Park'}, {id: '3-12', name: 'Petrified Forest National Park'}, {id: '3-13', name: 'Saguaro National Park'}],
  attractions: [{id: '3-21', name: 'Sedona'}, {id: '3-22', name: 'Monument Vally'}, {id: '3-23', name: 'Horseshoe Bend'}], 
  other: [{id: '3-31', name: 'Catologue Cacti'}, {id: '3-32', name: 'Star Gaze'}, {id: '3-33', name: 'Drive Along The Colorado River '}]},

  {id: '4', 
  name:'Arkansas', 
  abbreviation: 'AR', 
  capital: [{id: '4-c', name: 'Little Rock'}], 
  largestcity: [{id: '4-lc', name: 'Little Rock'}], 
  nationalparks: [{id: '4-11', name: 'Hot Springs National Park'}],
  attractions: [{id: '4-21', name: 'Gangster Museum of America'}, {id: '4-22', name: 'Little Rock Central High School National Historic Site'}], 
  other: [{id: '4-31', name: 'Camp In The Ozarks'}]},

  {id: '5', 
  name: 'California', 
  abbreviation: 'CA', 
  capital: [{id: '5-c', name: 'Sacramento'}], 
  largestcity: [{id: '5-lc', name: 'Los Angeles'}], 
  nationalparks: [{id: '5-11', name: 'Channel Islands National Park'}, {id: '5-12', name: 'Death Valley National Park'}, {id: '5-13', name: 'Joshua Tree National Park'}, {id: '5-14', name: 'Kings Canyon National Park'}, {id: '5-15', name: 'Lassen Volcanic National Park'}, {id: '5-16', name: 'Pinnacles National Park'}, {id: '5-17', name: 'Redwood National & State Parks'}, {id: '5-18', name: 'Sequoia National Park'}, {id: '5-19', name: 'Yosemite National Park'}],
  attractions: [{id: '5-21', name: 'Disneyland'}, {id: '5-22', name: 'Golden Gate Bridge'}, {id: '5-23', name: 'Alcatraz Island'}, {id: '5-24', name: 'Griffith Observatory'}, {id: '5-25', name: 'Lake Tahoe'}], 
  other: [{id: '5-31', name: 'Drive The Pacific Coast Highway'}, {id: '5-32', name: 'Drink Wine From California Wine Country'}]},

  {id: '6', 
  name: 'Colorado', 
  abbreviation: 'CO', 
  capital: [{id: '6-c', name: 'Denver'}], 
  largestcity: [{id: '6-lc', name: 'Denver'}], 
  nationalparks: [{id: '6-11', name: 'Black Canyon of the Gunnison National Park'}, {id: '6-12', name: 'Great Sand Dunes National Park'}, {id: '6-13', name: 'Mesa Verde National Park'}, {id: '6-14', name: 'Rocky Mountain National Park'}],
  attractions: [{id: '6-21', name: 'Garden of The Gods'}, {id: '6-22', name: 'Eldorado Canyon State Park'}, {id: '6-23', name: ''}, {id: '6-24', name: ''}, {id: '6-25', name: ''}], 
  other: [{id: '6-31', name: 'See a Concert at Red Rocks'}, {id: '6-32', name: 'Hike Above 14,000 ft'}, {id: '6-33', name: 'Go Skiing'}, {id: '6-34', name: 'Visit a Ghost Town'},]},

  {id: '7', 
  name: 'Connecticut', 
  abbreviation: 'CT', 
  capital: [{id: '7-c', name: 'Hartford'}], 
  largestcity: [{id: '7-lc', name: 'Bridgeport'}], 
  nationalparks: [{id: '7-11', name: 'null'}],
  attractions: [{id: '7-21', name: 'Mark Twain House and Museum'}, {id: '7-22', name: 'Gillette Castle State Park'}], 
  other: [{id: '7-31', name: 'Eat Local Pizzz'}, {id: '7-32', name: 'Explore The Beaches'}]},

  {id: '8', 
  name: 'Delaware', 
  abbreviation: 'DE', 
  capital: [{id: '8-c', name: 'Dover'}], 
  largestcity: [{id: '8-lc', name: 'Wilmington'}], 
  nationalparks: [{id: '8-11', name: 'null'}],
  attractions: [{id: '8-21', name: 'Cape Henlopen State Park'}, {id: '8-22', name: 'Fort Delaware State Park'}], 
  other: [{id: '8-31', name: 'Eat Blue Crab'}]},

  {id: '9', 
  name: 'Florida', 
  abbreviation: 'FL', 
  capital: [{id: '9-c', name: 'Tallahassee'}], 
  largestcity: [{id: '9-lc', name: 'Jacksonville'}], 
  nationalparks: [{id: '9-11', name: 'Biscayne National Park'}, {id: '9-12', name: 'Dry Tortugas National Park'}, {id: '9-13', name: 'Everglades National Park'}],
  attractions: [{id: '9-21', name: 'Disney World'}, {id: '9-22', name: 'Universal Orlando Resort'}, {id: '9-23', name: 'Blue Springs State Park'}], 
  other: [{id: '9-31', name: 'Explore The Florida Keys'}, {id: '9-32', name: 'Eat Seafood'}]},

  {id: '10', 
  name: 'Georgia', 
  abbreviation: 'GA', 
  capital: [{id: '10-c', name: 'Atlanta'}], 
  largestcity: [{id: '10-lc', name: 'Atlanta'}], 
  nationalparks: [{id: '10-11', name: 'null'}],
  attractions: [{id: '10-21', name: 'World of Coca-Cola'}, {id: '10-22', name: 'Visit Savannah'}, {id: '10-23', name: 'Stone Mountain'}], 
  other: [{id: '10-31', name: 'Eat A Georgia Peach'}]},

  {id: '11', 
  name: 'Hawaii', 
  abbreviation: 'HI', 
  capital: [{id: '11-c', name: 'Honolulu'}], 
  largestcity: [{id: '11-lc', name: 'Honolulu'}], 
  nationalparks: [{id: '11-11', name: 'Haleakalā National Park'}, {id: '11-12', name: 'Hawaii Volcanoes National Park'}],
  attractions: [{id: '11-21', name: 'Diamond Head'}, {id: '11-22', name: 'Pearl Harbor National Memorial'}, {id: '11-23', name: 'Waimea Canyon'}], 
  other: [{id: '11-31', name: 'Visit a Black Sand Beach'}, {id: '11-32', name: 'Go To a Luau'}]},

  {id: '12', 
  name: 'Idaho', 
  abbreviation: 'ID', 
  capital: [{id: '12-c', name: 'Boise'}], 
  largestcity: [{id: '12-lc', name: 'Boise'}], 
  nationalparks: [{id: '12-11', name: 'Yellowstone National Park'}],
  attractions: [{id: '12-21', name: 'Shoshone Falls Park'}, {id: '12-22', name: 'Craters of The Moon National Monument and Preserve'}, {id: '12-23', name: 'Idaho Potato Museum'}], 
  other: [{id: '12-31', name: 'Eat An Idaho Potato'}]},

  {id: '13', 
  name: 'Illinois', 
  abbreviation: 'IL', 
  capital: [{id: '13-c', name: 'Springfield'}], 
  largestcity: [{id: '13-lc', name: 'Chicago'}], 
  nationalparks: [{id: '13-11', name: 'null'}],
  attractions: [{id: '13-21', name: 'The Art Institute Of Chicago'}, {id: '13-22', name: 'Cloud Gate'}, {id: '13-23', name: 'River Walk'}, {id: '13-24', name: 'Lincoln Home National Historic Site'}], 
  other: [{id: '13-31', name: 'Eat a Chicago Style Hot Dog'}, {id: '13-32', name: 'Walk Along Lake Michigan'}]},

  {id: '14', 
  name: 'Indiana', 
  abbreviation: 'IN', 
  capital: [{id: '14-c', name: 'Indianapolis'}], 
  largestcity: [{id: '14-lc', name: 'Indianapolis'}], 
  nationalparks: [{id: '14-11', name: 'Indiana Dunes National Park'}],
  attractions: [{id: '14-21', name: 'Lincoln Boyhood National Memorial'}, {id: '14-22', name: 'Turkey Run State Park'}], 
  other: [{id: '14-31', name: 'Go See a Race At The Indianapolis Motor Speedway'}]},

  {id: '15', 
  name: 'Iowa', 
  abbreviation: 'IA', 
  capital: [{id: '15-c', name: 'Des Moines'}], 
  largestcity: [{id: '15-lc', name: 'Des Moines'}], 
  nationalparks: [{id: '15-11', name: 'null'}],
  attractions: [{id: '15-21', name: 'Maquoketa Caves State Park'}, {id: '15-22', name: 'Effigy Mounds National Monument'}, {id: '15-23', name: 'National Mississippi River Museum & Aquarium'}], 
  other: [{id: '15-31', name: 'Eat Some Iowa Corn'}]},
  
  {id: '16', 
  name: 'Kansas', 
  abbreviation: 'KS', 
  capital: [{id: '16-c', name: 'Topeka'}], 
  largestcity: [{id: '16-lc', name: 'Wichita'}], 
  nationalparks: [{id: '16-11', name: 'null'}],
  attractions: [{id: '16-21', name: 'OZ Museum'}, {id: '16-22', name: 'Dwight D. Eisenhower Presidential Library & Museum'}, {id: '16-23', name: 'Brown v. Board of Education National Historical Park'}], 
  other: [{id: '16-31', name: 'Eat Kansas BBQ'}]},

  {id: '17', 
  name: 'Kentucky', 
  abbreviation: 'KY', 
  capital: [{id: '17-c', name: 'Frankfort'}], 
  largestcity: [{id: '17-lc', name: 'Louisville'}], 
  nationalparks: [{id: '17-11', name: 'Mammoth Cave National Park'}],
  attractions: [{id: '17-21', name: 'Cumberland Falls State Resort Park'}, {id: '17-22', name: 'Red River Gorge Geological Area'}, {id: '17-23', name: 'National Corvette Museum'}], 
  other: [{id: '17-31', name: 'Do The Kentucky Bourbon Trail'}, {id: '17-32', name: 'Go To The Kentucky Derby'}]},

  {id: '18', 
  name: 'Louisiana', 
  abbreviation: 'LA', 
  capital: [{id: '18-c', name: 'Baton Rouge'}], 
  largestcity: [{id: '18-lc', name: 'New Orleans'}], 
  nationalparks: [{id: '18-11', name: 'null'}],
  attractions: [{id: '18-21', name: 'The National WWII Museum'}, {id: '18-22', name: 'Grand Isle State Park'}], 
  other: [{id: '18-31', name: 'Eat Gumbo'}, {id: '18-32', name: 'Attend Mardi Gras'}, {id: '18-33', name: 'Listen To Live Music In The Streets'}]},

  {id: '19', 
  name: 'Maine', 
  abbreviation: 'ME', 
  capital: [{id: '19-c', name: 'Augusta'}], 
  largestcity: [{id: '19-lc', name: 'Portland'}], 
  nationalparks: [{id: '19-11', name: 'Acadia National Park'}],
  attractions: [{id: '19-21', name: 'Portland Head Light'}, {id: '19-22', name: 'Mount Katahdin'}, {id: '19-23', name: 'Popham Beach State Park'}], 
  other: [{id: '19-31', name: 'Eat a Whoopie Pie'}]},

  {id: '20', 
  name: 'Maryland', 
  abbreviation: 'MD', 
  capital: [{id: '20-c', name: 'Annapolis'}], 
  largestcity: [{id: '20-lc', name: 'Baltimore'}], 
  nationalparks: [{id: '20-11', name: 'null'}],
  attractions: [{id: '20-21', name: 'Fort McHenry National Monument and Historic Shrine'}, {id: '20-22', name: 'Harriet Tubman Underground Railroad National Historical Park'}, {id: '20-23', name: 'Great Falls Park'}], 
  other: [{id: '20-31', name: 'Eat Crab Cakes'}]},

  {id: '21', 
  name: 'Massachusetts', 
  abbreviation: 'MA', 
  capital: [{id: '21-c', name: 'Boston'}], 
  largestcity: [{id: '21-lc', name: 'Boston'}], 
  nationalparks: [{id: '21-11', name: 'null'}],
  attractions: [{id: '21-21', name: 'Freedom Trail'}, {id: '21-22', name: 'Visit Boston Harbor'}, {id: '21-23', name: 'Visit Salem'}], 
  other: [{id: '21-31', name: 'Drink Wine At Marthas Vinyard'}]},

  {id: '22', 
  name: 'Michigan', 
  abbreviation: 'MI', 
  capital: [{id: '22-c', name: 'Lansing'}], 
  largestcity: [{id: '22-lc', name: 'Detroit'}], 
  nationalparks: [{id: '22-11', name: 'Isle Royale National Park'}],
  attractions: [{id: '22-21', name: 'Sleeping Bear Dunes National Lakeshore'}, {id: '22-22', name: 'Pictured Rocks National Lakeshore'}], 
  other: [{id: '22-31', name: 'Swim In a Great Lake'}, {id: '22-32', name: 'Eat Some Pasties'}]},

  {id: '23', 
  name: 'Minnesota', 
  abbreviation: 'MN', 
  capital: [{id: '23-c', name: 'St. Paul'}], 
  largestcity: [{id: '23-lc', name: 'Minneapolis'}], 
  nationalparks: [{id: '23-11', name: 'Voyageurs National Park'}],
  attractions: [{id: '1-21', name: ''}, {id: '1-22', name: ''}, {id: '1-23', name: ''}, {id: '1-24', name: ''}, {id: '1-25', name: ''}], 
  other: [{id: '1-31', name: ''}, {id: '1-32', name: ''}, {id: '1-33', name: ''}, {id: '1-34', name: ''}, {id: '1-35', name: ''}]},

  {id: '24', 
  name: 'Mississippi', 
  abbreviation: 'MS', 
  capital: [{id: '24-c', name: 'Jackson'}], 
  largestcity: [{id: '24-lc', name: 'Jackson'}], 
  nationalparks: [{id: '24-11', name: 'null'}],
  attractions: [{id: '24-21', name: 'Gooseberry Falls State Park'}, {id: '24-22', name: 'Mall Of America'}, {id: '24-23', name: 'Split Rock Lighthouse'}], 
  other: [{id: '24-31', name: 'Kayak or Canoe In a Lake'}]},

  {id: '25', 
  name: 'Missouri', 
  abbreviation: 'MO', 
  capital: [{id: '25-c', name: 'Jefferson City'}], 
  largestcity: [{id: '25-lc', name: 'Kansas City'}], 
  nationalparks: [{id: '25-11', name: 'Gateway Arch National Park'}],
  attractions: [{id: '25-21', name: 'The Nelson-Atkins Museum of Art'}, {id: '25-22', name: 'National WWI Museum and Memorial'}, {id: '25-23', name: 'Missouri Botanical Garden'}], 
  other: [{id: '25-31', name: 'Drink a Beer From Anheuser-Busch'}, {id: '25-32', name: 'Kayak Or Canoe The Missouri River'}]},

  {id: '26', 
  name: 'Montana', 
  abbreviation: 'MT', 
  capital: [{id: '26-c', name: 'Helena'}], 
  largestcity: [{id: '26-lc', name: 'Billings'}], 
  nationalparks: [{id: '26-11', name: 'Glacier National Park'}, {id: '26-12', name: 'Yellowstone National Park'}],
  attractions: [{id: '26-21', name: 'Bannack State Park'}], 
  other: [{id: '26-31', name: 'Eat a Bison Burger'}, {id: '26-32', name: 'Take Pictures Of Wildlife'}]},

  {id: '27', 
  name: 'Nebraska', 
  abbreviation: 'NE', 
  capital: [{id: '27-c', name: 'Lincoln'}], 
  largestcity: [{id: '27-lc', name: 'Omaha'}], 
  nationalparks: [{id: '27-11', name: 'null'}],
  attractions: [{id: '27-21', name: 'Omahas Henry Doorly Zoo and Aquarium'}, {id: '27-22', name: 'Scotts Bluff National Monument'}, {id: '27-23', name: 'Carhenge'}], 
  other: [{id: '27-31', name: 'Eat Runza'}]},

  {id: '28', 
  name: 'Nevada', 
  abbreviation: 'NV', 
  capital: [{id: '28-c', name: 'Carson City'}], 
  largestcity: [{id: '28-lc', name: 'Las Vegas'}], 
  nationalparks: [{id: '28-11', name: 'Death Valley National Park'}, {id: '28-12', name: 'Great Basin National Park'}],
  attractions: [{id: '28-21', name: 'Hoover Dam'}, {id: '28-22', name: 'Valley of Fire State Park'}], 
  other: [{id: '28-31', name: 'Play Cards At a Casino'}, {id: '28-32', name: 'Walk The Vegas Strip'}]},

  {id: '29', 
  name: 'New Hampshire', 
  abbreviation: 'NH', 
  capital: [{id: '29-c', name: 'Concord'}], 
  largestcity: [{id: '29-lc', name: 'Manchester'}], 
  nationalparks: [{id: '29-11', name: 'null'}],
  attractions: [{id: '29-21', name: 'Flume Gorge'}, {id: '29-22', name: 'Hampton Beach State Park'}], 
  other: [{id: '29-31', name: 'Eat Clam Chowder'}]},

  {id: '30', 
  name: 'New Jersey', 
  abbreviation: 'NJ', 
  capital: [{id: '30-c', name: 'Trenton'}], 
  largestcity: [{id: '30-lc', name: 'Newark'}], 
  nationalparks: [{id: '30-11', name: 'null'}],
  attractions: [{id: '30-21', name: 'Lakota Wolf Preserve'}, {id: '30-22', name: 'Cape May Lighthouse'}, {id: '30-23', name: 'Six Flags Great Adventure'}], 
  other: [{id: '30-31', name: 'Eat Pizza'}]},

  {id: '31', 
  name: 'New Mexico', 
  abbreviation: 'NM', 
  capital: [{id: '31-c', name: 'Santa Fe'}], 
  largestcity: [{id: '31-lc', name: 'Albuquerque'}], 
  nationalparks: [{id: '31-11', name: 'Carlsbad Caverns National Park'}, {id: '31-12', name: 'White Sands National Park'}],
  attractions: [{id: '31-21', name: 'International UFO Museum and Research Center and Gift Shop'}, {id: '31-22', name: 'Bandelier National Monument'}, {id: '31-23', name: 'Petroglyph National Monument'}], 
  other: [{id: '31-31', name: 'Attend The Albuquerque International Balloon Fiesta'}, {id: '31-32', name: 'Eat Mexican Food'}]},

  {id: '32', 
  name: 'New York', 
  abbreviation: 'NY', 
  capital: [{id: '32-c', name: 'Albany'}], 
  largestcity: [{id: '32-lc', name: 'New York City'}], 
  nationalparks: [{id: '32-11', name: 'null'}],
  attractions: [{id: '32-21', name: 'Statue Of Liberty'}, {id:'32-22', name: 'Empire State Building'}, {id: '32-23', name: 'Niagara Falls'}], 
  other: [{id: '32-31', name: 'Eat New York Pizza'}, {id: '32-32', name: 'See a Broadway Show'}]},

  {id: '33', 
  name: 'North Carolina', 
  abbreviation: 'NC', 
  capital: [{id: '33-c', name: 'Raleigh'}], 
  largestcity: [{id: '33-lc', name: 'Charlotte'}], 
  nationalparks: [{id: '33-11', name: 'Great Smoky Mountains National Park'}],
  attractions: [{id: '33-21', name: 'Biltmore Estate'}, {id: '33-22', name: 'Wright Brothers National Memorial'}], 
  other: [{id: '33-31', name: 'Drive The Blue Ridge Parkway'}, {id: '33-32', name: 'Explore The Outer Banks'}]},

  {id: '34', 
  name: 'North Dakota', 
  abbreviation: 'ND', 
  capital: [{id: '34-c', name: 'Bismarck'}], 
  largestcity: [{id: '34-lc', name: 'Fargo'}], 
  nationalparks: [{id: '34-11', name: 'Theodore Roosevelt National Park'}],
  attractions: [{id: '34-21', name: 'Worlds Largest Buffalo Monument'}, {id: '34-22', name: 'Medora Musical'}], 
  other: [{id: '34-31', name: 'Explore The Grasslands'}, {id: '34-32', name: 'Eat Kuchen'}]},

  {id: '35', 
  name: 'Ohio', 
  abbreviation: 'OH', 
  capital: [{id: '35-c', name: 'Columbus'}], 
  largestcity: [{id: '35-lc', name: 'Columbus'}], 
  nationalparks: [{id: '35-11', name: 'Cuyahoga Valley National Park'}],
  attractions: [{id: '35-21', name: 'Cedar Point'}, {id: '35-22', name: 'Rock & Roll Hall of Fame'}], 
  other: [{id: '35-31', name: 'Eat Buckeyes'}, {id: '35-32', name: 'Cruise The Lake Erie Shoreline'}]},

  {id: '36', 
  name: 'Oklahoma', 
  abbreviation: 'OK', 
  capital: [{id: '36-c', name: 'Oklahoma City'}], 
  largestcity: [{id: '36-lc', name: 'Oklahoma City'}], 
  nationalparks: [{id: '36-11', name: 'null'}],
  attractions: [{id: '36-21', name: 'National Cowboy & Western Heritage Museum'}, {id: '36-22', name: 'Turner Falls'}, {id: '36-23', name: 'American Banjo Museum'}], 
  other: [{id: '36-31', name: 'Eat Chicken Fried Steak'}]},

  {id: '37', 
  name: 'Oregon', 
  abbreviation: 'OR', 
  capital: [{id: '37-c', name: 'Salem'}], 
  largestcity: [{id: '37-lc', name: 'Portland'}], 
  nationalparks: [{id: '37-11', name: 'Crater Lake National Park'}],
  attractions: [{id: '37-21', name: 'The Last Blockbuster'}, {id: '37-22', name: 'Silver Falls State Park'}, {id: '37-23', name: 'Columbia River Gorge National Scenic Area'}], 
  other: [{id: '37-31', name: 'Explore The Organ Coast'}]},

  {id: '38', 
  name: 'Pennsylvania', 
  abbreviation: 'PA', 
  capital: [{id: '38-c', name: 'Harrisburg'}], 
  largestcity: [{id: '38-lc', name: 'Philadelphia'}], 
  nationalparks: [{id: '38-11', name: 'null'}],
  attractions: [{id: '38-21', name: 'Hersheypark'}, {id: '38-22', name: 'Presque Isle State Park'}, {id: '38-23', name: 'The Andy Warhol Museum'}, {id: '38-24', name: 'Independence National Historical Park'}], 
  other: [{id: '38-31', name: 'Explore Early American Architecture'}, {id: '38-32', name: 'Eat a Cheesteak'}]},

  {id: '39', 
  name: 'Rhode Island', 
  abbreviation: 'RI', 
  capital: [{id: '39-c', name: 'Providence'}], 
  largestcity: [{id: '39-lc', name: 'Providence'}], 
  nationalparks: [{id: '39-11', name: 'null'}],
  attractions: [{id: '39-21', name: 'Fort Adams State Park'}, {id: '39-22', name: 'Castle Hill Lighthouse'}], 
  other: [{id: '39-31', name: 'Walk The Coast'}]},

  {id: '40', 
  name: 'South Carolina', 
  abbreviation: 'SC', 
  capital: [{id: '40-c', name: 'Columbia'}], 
  largestcity: [{id: '40-lc', name: 'Columbia'}], 
  nationalparks: [{id: '40-11', name: 'Congaree National Park'}],
  attractions: [{id: '40-21', name: 'Falls Park on the Reedy'}, {id: '40-22', name: 'Charleston City Market'}], 
  other: [{id: '40-31', name: 'Visit All The Major Islands In SC'}, {id: '40-32', name: 'Eat Shrimp And Grits'}]},
  
  {id: '41', 
  name: 'South Dakota', 
  abbreviation: 'SD', 
  capital: [{id: '41-c', name: 'Pierre'}], 
  largestcity: [{id: '41-lc', name: 'Sioux Falls'}], 
  nationalparks: [{id: '41-11', name: 'Badlands National Park'}, {id: '41-12', name: 'Wind Cave National Park'}],
  attractions: [{id: '41-21', name: 'Mt. Rushmore'}, {id: '41-22', name: 'Charleston City Market'}, {id: '41-23', name: 'Jewel Cave National Monument'}], 
  other: [{id: '41-31', name: 'Eat Chislic'}]},

  {id: '42', 
  name: 'Tennessee', 
  abbreviation: 'TN', 
  capital: [{id: '42-c', name: 'Nashville'}], 
  largestcity: [{id: '42-lc', name: 'Memphis'}], 
  nationalparks: [{id: '42-11', name: 'Great Smoky Mountains National Park'}],
  attractions: [{id: '42-21', name: 'Country Music Hall of Fame and Museum'}, {id: '42-22', name: 'The Parthenon'}], 
  other: [{id: '42-31', name: 'Listen To Live Music In Nasheville'}]},

  {id: '43', 
  name: 'Texas', 
  abbreviation: 'TX', 
  capital: [{id: '43-c', name: 'Austin'}], 
  largestcity: [{id: '43-lc', name: 'Houston'}], 
  nationalparks: [{id: '43-11', name: 'Big Bend National Park'}, {id: '43-12', name: 'Guadalupe Mountains National Park'}],
  attractions: [{id: '43-21', name: 'The Alamo'}, {id: '43-22', name: 'Palo Duro Canyon State Park'}], 
  other: [{id: '43-31', name: 'Explore Dallas Fort Worth Area'}, {id: '43-32', name: 'Eat Chili Con Carne'}]},

  {id: '44', 
  name: 'Utah', 
  abbreviation: 'UT', 
  capital: [{id: '44-c', name: 'Salt Lake City'}], 
  largestcity: [{id: '44-lc', name: 'Salt Lake City'}], 
  nationalparks: [{id: '44-11', name: 'Arches National Park'}, {id: '45-12', name: 'Bryce Canyon National Park'}, {id: '44-13', name: 'Canyonlands National Park'}, {id: '44-14', name: 'Capitol Reef National Park'}, {id: '44-15', name: 'Zion National Park'}],
  attractions: [{id: '44-21', name: 'Dead Horse Point State Park'}, {id: '44-22', name: 'Grand Staircase-Escalante National Monument'}], 
  other: [{id: '44-31', name: 'Eat A Pastrami Burger'}]},

  {id: '45', 
  name: 'Vermont', 
  abbreviation: 'VT', 
  capital: [{id: '45-c', name: 'Montpelier'}], 
  largestcity: [{id: '45-lc', name: 'Burlington'}], 
  nationalparks: [{id: '45-11', name: 'null'}],
  attractions: [{id: '45-21', name: 'Hildene, The Lincoln Family Home'}, {id: '45-22', name: 'Lake Champlain'}], 
  other: [{id: '45-31', name: 'Eat Vermont Maple Syrup'}]},

  {id: '46', 
  name: 'Virginia', 
  abbreviation: 'VA', 
  capital: [{id: '46-c', name: 'Richmond'}], 
  largestcity: [{id: '46-lc', name: 'Virginia Beach'}], 
  nationalparks: [{id: '46-11', name: 'Shenandoah National Park'}],
  attractions: [{id: '46-21', name: 'Busch Gardens Williamsburg'}, {id: '46-22', name: 'George Washingtons Mount Vernon'}], 
  other: [{id: '46-31', name: 'Drive The Blue Ridge Parkway'}]},

  {id: '47', 
  name: 'Washington', 
  abbreviation: 'WA', 
  capital: [{id: '47-c', name: 'Olympia'}], 
  largestcity: [{id: '47-lc', name: 'Seattle'}], 
  nationalparks: [{id: '47-11', name: 'Mount Rainier National Park'}, {id: '47-12', name: 'North Cascades National Park'}, {id: '47-13', name: 'Olympic National Park'}],
  attractions: [{id: '47-21', name: 'Space Needle'}], 
  other: [{id: '47-31', name: 'Explore The Olympic Pennensula'}, {id: '47-32', name: 'Catalogue Trees'}]},

  {id: '48', 
  name: 'West Virginia', 
  abbreviation: 'WV', 
  capital: [{id: '48-c', name: 'Charleston'}], 
  largestcity: [{id: '48-lc', name: 'Charleston'}], 
  nationalparks: [{id: '48-11', name: 'New River Gorge National Park and Preserve'}],
  attractions: [{id: '48-21', name: 'Blackwater Falls State Park'}, {id: '48-22', name: 'Babcock State Park'}], 
  other: [{id: '48-31', name: 'Eat a Pepperoni Roll'}]},

  {id: '49', 
  name: 'Wisconsin', 
  abbreviation: 'WI', 
  capital: [{id: '49-c', name: 'Madison'}], 
  largestcity: [{id: '49-lc', name: 'Milwaukee'}], 
  nationalparks: [{id: '49-11', name: 'null'}],
  attractions: [{id: '49-21', name: 'Olbrich Botanical Gardens'}, {id: '49-22', name: 'Devils Lake State Park'}], 
  other: [{id: '49-31', name: 'Eat Cheese Curds'}]},

  {id: '50', 
  name: 'Wyoming', 
  abbreviation: 'WY', 
  capital: [{id: '50-c', name: 'Cheyenne'}], 
  largestcity: [{id: '50-lc', name: 'Cheyenne'}], 
  nationalparks: [{id: '50-11', name: 'Grand Teton National Park'}, {id: '50-12', name: 'Yellowstone National Park'}],
  attractions: [{id: '50-21', name: 'Devils Tower National Monument'}, {id: '50-22', name: 'Hot Springs State Park'}], 
  other: [{id: '50-31', name: 'View Wildlife'}]}
];